/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package multi_keyboard0;

import org.jline.*;

public class App {
    public static void main(String[] args) {
        Terminal_cmd terminal = new Terminal_cmd();
        terminal.setLanguage();
    }
}

class KeyBoardConfig {
    String availableLanguages;
    KeyBoardConfig() {

    }
    String checkAvailableLanguages() {
        return availableLanguages;
    }
    void parseKeyBoardConfig() {}
    void showConfigJson() {}
    void showConfigError() {}
}

